Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2022-05, with the labels that each got.

#31 Documentation on using AzureAuth CLI
  README.md
  docs/usage.md
Labels: documentation

#58 Collect auth settings and arg validation status in telemetry.
  CHANGELOG.md
  src/AzureAuth/CommandMain.cs
Labels: enhancement

#61 Fix broken macOS symlinks
  install/install.sh
Labels: bug

#59 Mac ESRP script update
  bin/mac_esrp_signing/dll_signing.py
  bin/mac_esrp_signing/dylibs_signing.py
Labels: bug

#53 XML comment clean up in MSALWrapper and MSALWrapperTest
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper.Test/PCAWrapperTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowExecutor.cs
  src/MSALWrapper/AuthFlow/AuthFlowResult.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/IAuthFlow.cs
  src/MSALWrapper/AuthFlow/Web.cs
  src/MSALWrapper/AuthMode.cs
  src/MSALWrapper/AuthenticationTimeoutException.cs
  src/MSALWrapper/ExceptionExtensions.cs
  src/MSALWrapper/ExceptionListToStringConverter.cs
  src/MSALWrapper/IPCAWrapper.cs
  src/MSALWrapper/ITokenFetcher.cs
  src/MSALWrapper/JsonWebTokenExtensions.cs
  src/MSALWrapper/MsalHttpClientFactoryAdaptor.cs
  src/MSALWrapper/PCAWrapper.cs
  src/MSALWrapper/TokenResult.cs
Labels: documentation

#65 Return NullTokenResultException when the authflow returns null.
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowExecutor.cs
  src/MSALWrapper/AuthFlow/NullTokenResultException.cs
Labels: enhancement

#69 Fix installation script when PATH not exists
  install/install.ps1
Labels: bug

#67 Add a release workflow
  .github/workflows/release.yml
  bin/sign.py
  bin/version.py
Labels: enhancement

#75 Check out code to use scripts
  .github/workflows/release.yml
Labels: bug

#77 Setup .NET 5
  .github/workflows/release.yml
Labels: bug

#78 Making signing runtime support win10-x64
  bin/sign.py
Labels: bug
