Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2022-04, with the labels that each got.

#8 add comments for AzureAuth project
  src/AzureAuth/Alias.cs
  src/AzureAuth/CommandMain.cs
  src/AzureAuth/Config.cs
  src/AzureAuth/Program.cs
Labels: documentation

#10 Remove short flags
  CHANGELOG.md
  src/AzureAuth.Test/CommandMainTest.cs
  src/AzureAuth/CommandMain.cs
Labels: documentation, enhancement

#12 Rename --auth-mode to --mode
  src/AzureAuth/CommandMain.cs
Labels: enhancement

#13 Mention --auth-mode to --mode change in CHANGELOG.md
  CHANGELOG.md
Labels: documentation

#14 Add installation scripts
  README.md
  install/install.ps1
  install/install.sh
Labels: enhancement

#23 Always add newlines around *nix $PATH updates
  install/install.sh
Labels: bug

#35 Update to MSAL 4.43.1
  CHANGELOG.md
  examples/Demo.Console.NETFramework472/Demo.Console.NETFramework472.csproj
  src/MSALWrapper/MSALWrapper.csproj
Labels: bug

#36 Only write token output directly to stdout
  CHANGELOG.md
  src/AzureAuth/CommandMain.cs
Labels: bug, security

#37 Update docs to reflect v0.2.0 release
  CHANGELOG.md
  README.md
Labels: documentation

#38 Fix errors in ESRP signing scripts
  bin/mac_esrp_signing/dll_signing.py
  bin/mac_esrp_signing/dylibs_signing.py
  bin/run_esrp_signing.py
Labels: bug

#34 AuthFlowExecutor that orchestrates different auth flows to get token and collect errors
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowResultTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowExecutor.cs
  src/MSALWrapper/AuthFlow/AuthFlowResult.cs
Labels: enhancement

#42 Ignore createdump
  install/install.sh
Labels: bug

#39 Web Auth Flow
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper/AuthFlow/Web.cs
  src/MSALWrapper/MsalHttpClientFactoryAdaptor.cs
Labels: enhancement

#41 Device Code Auth Flow
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
Labels: enhancement

#45 Provide an alternative installation directory
  README.md
  install/install.ps1
  install/install.sh
Labels: documentation, enhancement

#48 Update CHANGELOG from recent set of refactors
  CHANGELOG.md
Labels: documentation

#49 Stop renaming directories, use directory junctions on Windows
  CHANGELOG.md
  install/install.ps1
  install/install.sh
Labels: bug

#50 Enable TLS 1.2 by default
  install/install.ps1
Labels: bug
