Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2022-06, with the labels that each got.

#80 Actually make signing runtime support win10-x64
  bin/sign.py
Labels: bug

#84 Add certificates to the user store
  .github/workflows/release.yml
Labels: bug

#85 Use local machine certificates
  .github/workflows/release.yml
  bin/sign.py
Labels: bug

#86 Use a matrix strategy for signing
  .github/workflows/release.yml
  bin/sign.py
Labels: enhancement

#88 Add status badges
  README.md
Labels: documentation, enhancement

#87 Add executable bit again for appropriate files
  .github/workflows/release.yml
Labels: bug

#89 Remove outdated CI files
  bin/mac_esrp_signing/dll_signing.py
  bin/mac_esrp_signing/dylibs_signing.py
  bin/package.cmd
  bin/package.py
  bin/publish.cmd
  bin/publish.py
  bin/run_esrp_signing.py
  bin/versioning.py
Labels: enhancement

#90 Release v0.3.1
  CHANGELOG.md
Labels: documentation

#91 Change version scheme
  .github/workflows/release.yml
  CHANGELOG.md
  README.md
  bin/version.py
Labels: bug, documentation

#92 Fix windows archive errors
  .github/workflows/release.yml
  CHANGELOG.md
Labels: bug, documentation, devops

#94 Add a CODEOWNERS file
  .github/CODEOWNERS
Labels: documentation, enhancement

#93 Stop azureauth before install
  install/install.ps1
Labels: bug

#99 Stop azureauth before install
  install/install.ps1
Labels: bug

#97 docs: fix example config file in usage
  docs/usage.md
Labels: bug, documentation

#100 Avoid empty try-catch code block by using GetProcess
  install/install.ps1
Labels: refactor

#102 Wait after killing a task before removing the directory
  install/install.ps1
Labels: bug

#70 Adding Option and Environment variable for AzureAuth Cache file
  CHANGELOG.md
  src/AzureAuth.Test/CommandMainTest.cs
  src/AzureAuth/CommandMain.cs
  src/AzureAuth/EnvVars.cs
  src/AzureAuth/LegalFileChecker.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowFactoryTest.cs
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowFactory.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
  src/MSALWrapper/AuthFlow/Web.cs
  src/MSALWrapper/PCACache.cs
  src/MSALWrapper/PCAWrapper.cs
Labels: enhancement

#107 Add AuthFlowName to the AuthFlowResult
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowResultTest.cs
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowExecutor.cs
  src/MSALWrapper/AuthFlow/AuthFlowResult.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
  src/MSALWrapper/AuthFlow/Web.cs
Labels: enhancement

#109 Send AuthFlowResults to the CLI
  src/AzureAuth/CommandMain.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowExecutor.cs
Labels: enhancement

#111 Send AuthFlow Events from the AzureAuth CLI
  CHANGELOG.md
  src/AzureAuth.Test/CommandMainTest.cs
  src/AzureAuth/CommandMain.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowResultTest.cs
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper.Test/ExceptionListToStringConverterTest.cs
  src/MSALWrapper.Test/PCAWrapperTest.cs
  src/MSALWrapper.Test/TokenResultTest.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
  src/MSALWrapper/AuthFlow/Web.cs
  src/MSALWrapper/ExceptionListToStringConverter.cs
  src/MSALWrapper/PCAWrapper.cs
  src/MSALWrapper/TokenResult.cs
  src/MSALWrapper/TokenResultExtensions.cs
Labels: enhancement

#119 Improve code style in `ExceptionExtensions.cs`
  src/MSALWrapper.Test/ExceptionExtensionsTest.cs
  src/MSALWrapper/ExceptionExtensions.cs
Labels: refactor

#120 Update install.sh with post-0.4.0 install logic
  install/install.sh
Labels: bug

#122 Add some comments for clarity
  install/install.ps1
Labels: enhancement

#123 Explain setx usage
  install/install.ps1
Labels: enhancement

#115 Updating install scripts to no longer create latest
  .github/workflows/release.yml
  install/install.ps1
  install/install.sh
Labels: enhancement

#125 Default to 0.4.0 as example release
  README.md
Labels: documentation
