Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2022-09, with the labels that each got.

#137 Upgrade CompleteWithin to forcefully timeout
  CHANGELOG.md
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/Web.cs
  src/MSALWrapper/TaskExecutor.cs
Labels: bug

#143 Increase the initial warning delay to 20 seconds
  src/MSALWrapper/AuthFlow/AuthFlowExecutor.cs
Labels: enhancement

#144 Update release and download badges
  README.md
Labels: enhancement

#145 Send auth flow events before early exiting when no success events exist
  src/AzureAuth.Test/CommandMainTest.cs
  src/AzureAuth/CommandMain.cs
  src/MSALWrapper/ITokenFetcher.cs
Labels: bug

#149 Adding section in usage docs for setting custom timeout
  docs/usage.md
Labels: documentation

#142 AzureAuth: --resource should not be required if passing scopes
  CHANGELOG.md
  src/AzureAuth.Test/CommandMainTest.cs
  src/AzureAuth/CommandMain.cs
Labels: enhancement
