Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2022-07, with the labels that each got.

#126 Added screenshots to platform configurations
  docs/mobile-desktop-platform-config.png
  docs/public-client-flows.png
  docs/usage.md
  docs/web-platform-config.png
Labels: documentation

#128 Provide a way to disable user based authentication on non-user based environments
  CHANGELOG.md
  src/AzureAuth.Test/AzureAuth.Test.csproj
  src/AzureAuth.Test/CommandMainTest.cs
  src/AzureAuth/CommandMain.cs
  src/AzureAuth/EnvVars.cs
Labels: enhancement

#130 Use double quotes to allow interpolation
  README.md
Labels: bug, documentation

#127 Adding global timeout and timeout warnings
  CHANGELOG.md
  src/AzureAuth/CommandMain.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper.Test/StopwatchTrackerTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowExecutor.cs
  src/MSALWrapper/IStopwatch.cs
  src/MSALWrapper/StopwatchTracker.cs
  src/MSALWrapper/TaskExecutor.cs
Labels: enhancement
