Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2023-03, with the labels that each got.

#198 Add CodeQL.yml in Pull Request process to enable static analysis
  .github/workflows/dotnet-test.yml
Labels: security, devops

#219 [Urgent] Fix GitHub workflow.
  .github/workflows/dotnet-test.yml
Labels: bug, devops

#199 Add CodeQL in release workflow
  .github/workflows/release.yml
Labels: security, devops

#212 Add unlit PatManager and supporting interfaces
  src/AdoPat.Test/PatCacheTest.cs
  src/AdoPat.Test/PatClientTest.cs
  src/AdoPat.Test/PatManagerTest.cs
  src/AdoPat/IPatCache.cs
  src/AdoPat/IPatClient.cs
  src/AdoPat/PatCache.cs
  src/AdoPat/PatClient.cs
  src/AdoPat/PatManager.cs
  src/AdoPat/PatOptions.cs
Labels: enhancement

#214 Create functional `TokenFetcher` orchestrator for AAD and Azure Devops
  src/AzureAuth.Test/Ado/PatFromEnvTest.cs
  src/AzureAuth.Test/AzureAuth.Test.csproj
  src/AzureAuth/Ado/Constants.cs
  src/AzureAuth/Ado/PatFromEnv.cs
  src/AzureAuth/Ado/TokenFetcher.cs
  src/AzureAuth/AzureAuth.csproj
  src/AzureAuth/Commands/Ado/CommandToken.cs
  src/MSALWrapper.Test/MSALWrapper.Test.csproj
  src/MSALWrapper/MSALWrapper.csproj
  src/MSALWrapper/TokenFetcher.cs
Labels: enhancement, refactor

#216 Extract Prompt Hint to pure function
  src/AzureAuth.Test/CommandAadTest.cs
  src/AzureAuth.Test/PromptHintTest.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/AzureAuth/PromptHint.cs
Labels: refactor

#217 Extract AuthFlowResult conversion to Telemetry into Extension Methods for Reuse
  src/AzureAuth.Test/AuthFlowResultExtensionsTest.cs
  src/AzureAuth.Test/CommandAadTest.cs
  src/AzureAuth/AuthFlowResultExtensions.cs
  src/AzureAuth/Commands/CommandAad.cs
Labels: refactor

#210 Upgrade Lasso and match the API changes.
  src/AzureAuth/AzureAuth.csproj
  src/AzureAuth/Commands/CommandInfo.cs
  src/AzureAuth/Commands/Info/CommandInfoResetDeviceID.cs
Labels: bug, enhancement

#220 Update ChangeLog.md for release 0.7.1
  CHANGELOG.md
Labels: documentation, devops

#218 Extract auth mode interaction filtering into static methods for reuse
  src/AzureAuth.Test/AuthModeExtensionsTest.cs
  src/AzureAuth.Test/CommandAadTest.cs
  src/AzureAuth.Test/IEnvExtensionsTest.cs
  src/AzureAuth/Ado/PatFromEnv.cs
  src/AzureAuth/AuthModeExtensions.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/AzureAuth/EnvVars.cs
  src/AzureAuth/IEnvExtensions.cs
Labels: refactor

#215 Download ADO artifacts after triggering ADO pipeline
  bin/trigger_azure_pipelines.py
Labels: devops

#211 Update release workflow to release Linux binaries
  .github/workflows/release.yml
Labels: devops

#221 Break apart AuthMode Extensions
  src/AzureAuth.Test/AuthModeExtensionsTest.cs
  src/AzureAuth/AuthModeExtensions.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/MSALWrapper/AuthMode.cs
Labels: enhancement, refactor

#222 Use TokenFetcher in CommandAad
  bin/azureauth
  bin/azureauth.cmd
  bin/win_publish.cmd
  src/AzureAuth.Test/CommandAadTest.cs
  src/AzureAuth/Ado/TokenFetcher.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/MSALWrapper/TokenFetcher.cs
Labels: bug, refactor

#225 Release 0.7.2 with Lasso patch version
  CHANGELOG.md
  src/AzureAuth/AzureAuth.csproj
Labels: bug, devops

#226 Revert "Update release workflow to release Linux binaries"
  .github/workflows/release.yml
Labels: bug, devops

#227 Add a Token Formatter
  src/AzureAuth.Test/Ado/TokenFormattingExtensionsTest.cs
  src/AzureAuth/Ado/Authorization.cs
  src/AzureAuth/Ado/TokenFormattingExtensions.cs
Labels: enhancement

#231 Set CodeQL in another job
  .github/workflows/dotnet-test.yml
Labels: devops

#232 Fix GitHub workflow for CodeQL
  .github/workflows/dotnet-test.yml
Labels: bug, devops

#230 Update Readme For 0.7.2
  README.md
Labels: documentation, devops

#234 [urgent]Remove scopes in the lock name because scopes may contains `/`
  CHANGELOG.md
  src/MSALWrapper/TokenFetcher.cs
Labels: bug, urgent

#235 Upload CodeQL result to artifact.
  .github/workflows/release.yml
Labels: devops

#228 Initial work to get `ado token` command working.
  src/AzureAuth.Test/Commands/Ado/CommandTokenTest.cs
  src/AzureAuth/Ado/TokenFormattingExtensions.cs
  src/AzureAuth/Commands/Ado/CommandToken.cs
  src/AzureAuth/Commands/CommandAzureAuth.cs
Labels: enhancement

#239 Update Readme to 0.7.3
  README.md
Labels: documentation, devops

#240 unlight ado command
  src/AzureAuth/Commands/CommandAzureAuth.cs
Labels: refactor

#241 [1/3] 🏝️ Isolate and test Mutex in standalone class `Locked`
  src/MSALWrapper.Test/LockedTest.cs
  src/MSALWrapper/Locked.cs
Labels: enhancement

#242 [2/3] 🦺 Assert lock names are safe
  src/MSALWrapper.Test/LockedTest.cs
  src/MSALWrapper/Locked.cs
Labels: enhancement

#243 [3/3] 🧠 Use an in-memory `ILogger` to make stronger Mutex assertions
  src/MSALWrapper.Test/LockedTest.cs
Labels: enhancement

#244 🪛 fix test assertion and namespaces
  src/MSALWrapper.Test/AuthFlow/AuthFlowFactoryTest.cs
  src/MSALWrapper.Test/LockedTest.cs
  src/MSALWrapper.Test/MSALWrapper.Test.csproj
  src/MSALWrapper.Test/StopwatchTrackerTest.cs
Labels: bug

#247 [1/n] 📜 Move common in memory logger setup to shared method.
  AzureAuth.sln
  TestHelper/MemoryLogger.cs
  TestHelper/TestHelper.csproj
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowFactoryTest.cs
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper.Test/LockedTest.cs
  src/MSALWrapper.Test/MSALWrapper.Test.csproj
  src/MSALWrapper.Test/PCAWrapperTest.cs
Labels: refactor

#248 [2/n] Use 🔒 `Locked.Execute` from `TokenFetcher`
  bin/win/azureauth.cmd
  src/MSALWrapper/TokenFetcher.cs
Labels: enhancement, refactor

#250 [1/n] 📦 Move TokenFetcher method behind interface.
  src/AzureAuth/Ado/TokenFetcher.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/MSALWrapper/ITokenFetcher.cs
  src/MSALWrapper/TokenFetcher.cs
Labels: enhancement, refactor

#251 [2/n] 🍉 Create AuthOrchestrator (renamed in next PR)
  src/AzureAuth.Test/AuthOrchestratorTest.cs
  src/AzureAuth.Test/AzureAuth.Test.csproj
  src/AzureAuth/AuthOrchestrator.cs
Labels: enhancement

#252 [3/n] 🍓 Arrive at `PublicClientAuth` as AzureAuth's abstraction over `IMsalWrapper` (rename of `TokenFetcher`)
  src/AzureAuth.Test/AuthOrchestratorTest.cs
  src/AzureAuth.Test/PublicClientAuthTest.cs
  src/AzureAuth/Ado/TokenFetcher.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/AzureAuth/IPublicClientAuth.cs
  src/AzureAuth/PublicClientAuth.cs
  src/MSALWrapper/IMsalWrapper.cs
  src/MSALWrapper/MsalWrapper.cs
  src/TestHelper/Fake.cs
Labels: enhancement, refactor

#253 [4/n] 🎉 Use PublicClientAuth and Enable `azureauth ado token` command 🎊
  src/AdoPat.Test/PatManagerTest.cs
  src/AdoPat/PatOptions.cs
  src/AzureAuth.Test/AuthModeExtensionsTest.cs
  src/AzureAuth.Test/CommandAadTest.cs
  src/AzureAuth.Test/PublicClientAuthTest.cs
  src/AzureAuth/Ado/Constants.cs
  src/AzureAuth/Ado/PatFromEnv.cs
  src/AzureAuth/Ado/TokenFetcher.cs
  src/AzureAuth/AuthModeExtensions.cs
  src/AzureAuth/Commands/Ado/CommandToken.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/AzureAuth/Commands/CommandAdo.cs
  src/AzureAuth/Commands/CommandAzureAuth.cs
  src/AzureAuth/EnvVars.cs
  src/AzureAuth/IPublicClientAuth.cs
  src/AzureAuth/Program.cs
  src/AzureAuth/PublicClientAuth.cs
  src/stylecop/GlobalSuppressions.cs
Labels: enhancement

#254 [5/n] 🛠️ Address data clump with class.
  src/AzureAuth.Test/PublicClientAuthTest.cs
  src/AzureAuth/Ado/Constants.cs
  src/AzureAuth/Commands/Ado/CommandToken.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/AzureAuth/IPublicClientAuth.cs
  src/AzureAuth/PublicClientAuth.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowFactoryTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowFactory.cs
  src/MSALWrapper/AuthParameters.cs
  src/MSALWrapper/IMsalWrapper.cs
  src/MSALWrapper/MsalWrapper.cs
Labels: refactor

#257 Scaffold the ado pat subcommand
  src/AzureAuth/Commands/Ado/CommandPat.cs
Labels: enhancement

#258 Serialize PatTokens as pretty-printed JSON strings
  src/AdoPat.Test/PatTokenExtensionsTest.cs
  src/AdoPat/PatTokenExtensions.cs
Labels: enhancement

#259 Define PAT storage constants
  src/AzureAuth/Ado/Constants.cs
Labels: enhancement
