Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2023-01, with the labels that each got.

#172 Parse inner exception messages
  src/AzureAuth.Test/AzureAuth.Test.csproj
  src/AzureAuth.Test/CommandMainTest.cs
  src/AzureAuth.Test/ExceptionListToStringConverterTest.cs
  src/AzureAuth/CommandMain.cs
  src/AzureAuth/ExceptionListToStringConverter.cs
  src/MSALWrapper.Test/ExceptionListToStringConverterTest.cs
  src/MSALWrapper/ExceptionListToStringConverter.cs
Labels: enhancement

#180 changes to readme telemetry collection
  README.md
Labels: documentation

#181 Fix build badge on README
  .github/workflows/dotnet-test.yml
  README.md
Labels: documentation

#182 Add sid in telemetry
  CHANGELOG.md
  src/AzureAuth/CommandMain.cs
  src/MSALWrapper.Test/TokenResultTest.cs
  src/MSALWrapper/JsonWebTokenExtensions.cs
  src/MSALWrapper/TokenResult.cs
Labels: enhancement

#177 Pass template parameters when triggering a build on ADO
  bin/trigger_azure_pipelines.py
Labels: devops

#185 Collect env vars for Azure pipelines and Cloud Build Agent machines
  CHANGELOG.md
  src/AzureAuth/Program.cs
Labels: enhancement

#176 Add unlit Azure DevOps PAT client classes
  AzureAuth.sln
  src/AdoPat.Test/AdoPat.Test.csproj
  src/AdoPat.Test/PatClientTest.cs
  src/AdoPat/AdoPat.csproj
  src/AdoPat/ITokensHttpClientWrapper.cs
  src/AdoPat/PatClient.cs
  src/AdoPat/PatClientException.cs
  src/AdoPat/TokensHttpClientWrapper.cs
  src/stylecop/GlobalSuppressions.cs
Labels: enhancement

#183 Add unlit PAT caching classes
  src/AdoPat.Test/PatCacheTest.cs
  src/AdoPat/AdoPat.csproj
  src/AdoPat/IStorageWrapper.cs
  src/AdoPat/ITokensHttpClientWrapper.cs
  src/AdoPat/PatCache.cs
  src/AdoPat/StorageWrapper.cs
Labels: enhancement
