Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2023-05, with the labels that each got.

#286 [1/n] Consolidate Error Handling into `AuthFlowBase`
  src/MSALWrapper/AuthFlow/AuthFlowBase.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
  src/MSALWrapper/AuthFlow/Web.cs
Labels: refactor

#284 [2/n] Make CachedAuth an AuthFlow
  src/MSALWrapper.Test/AuthFlow/AuthFlowFactoryTest.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowTestBase.cs
  src/MSALWrapper.Test/AuthFlow/CachedAuthTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowFactory.cs
  src/MSALWrapper/AuthFlow/CachedAuth.cs
Labels: refactor

#287 [1/🗑️] Remove `CachedAuth` usage from IWA
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
  src/MSALWrapper/AuthFlow/Web.cs
Labels: refactor

#289 [2/🗑️] Remove `CachedAuth` usage from Web.
  src/MSALWrapper.Test/AuthFlow/AuthFlowTestBase.cs
  src/MSALWrapper.Test/AuthFlow/CachedAuthTest.cs
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowBase.cs
  src/MSALWrapper/AuthFlow/Web.cs
Labels: enhancement, refactor

#291 [3/🗑️] Remove `CachedAuth` from DeviceCode
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
Labels: enhancement, refactor

#292 [1/🧹] Fix async throw assertions
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
Labels: bug

#293 [2/🧹] Use abstract Property instead of method for `Name`.
  src/MSALWrapper/AuthFlow/AuthFlowBase.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/CachedAuth.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
  src/MSALWrapper/AuthFlow/Web.cs
Labels: refactor

#294 [3/🧹] Use `AuthParameters` in broker.
  src/MSALWrapper.Benchmark/BrokerBenchmark.cs
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowFactory.cs
  src/MSALWrapper/AuthFlow/Broker.cs
Labels: refactor

#295 [4/🧹] Use `AuthParameters` in cached auth.
  src/MSALWrapper.Test/AuthFlow/AuthFlowTestBase.cs
  src/MSALWrapper.Test/AuthFlow/CachedAuthTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowFactory.cs
  src/MSALWrapper/AuthFlow/CachedAuth.cs
Labels: refactor

#296 [5/🧹] Use `AuthParameters` in IWA.
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowFactory.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
Labels: refactor

#298 [7/🧹] Align `CachedAuthTest` with `AuthFlowTestBase`
  src/MSALWrapper.Test/AuthFlow/AuthFlowTestBase.cs
  src/MSALWrapper.Test/AuthFlow/CachedAuthTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
Labels: refactor

#299 [8/🧹] Align `BrokerTest` with `AuthFlowTestBase`
  src/MSALWrapper.Test/AuthFlow/AuthFlowTestBase.cs
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/CachedAuthTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
Labels: refactor

#300 [9/🧹] Linting and PR follow ups
  AzureAuth.sln
  src/AdoPat.Test/AdoPat.Test.csproj
  src/AdoPat/AdoPat.csproj
  src/AzureAuth.Test/AzureAuth.Test.csproj
  src/AzureAuth/AzureAuth.csproj
  src/AzureAuth/Commands/CommandAad.cs
  src/AzureAuth/IPublicClientAuth.cs
  src/MSALWrapper.Test/MSALWrapper.Test.csproj
  src/MSALWrapper/AuthFlow/AuthFlowBase.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/CachedAuth.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
  src/MSALWrapper/AuthFlow/Web.cs
  src/MSALWrapper/Constants.cs
  src/MSALWrapper/Locked.cs
  src/MSALWrapper/MSALWrapper.csproj
  src/TestHelper/MemoryLogger.cs
Labels: refactor

#301 Update dev scripts to call azureauth >= 0.8.0
  bin/mac/dotnet
  bin/win/dotnet.cmd
Labels: devops

#302 📜 Update CHANGELOG for recent bug fixes and refactor.
  CHANGELOG.md
Labels: documentation

#307 Modify CHANGELOG.md for incoming version 0.8.1
  CHANGELOG.md
Labels: documentation

#306 Bump requests from 2.28.1 to 2.31.0 in /bin (#305)
  bin/requirements.txt
Labels: security, dependencies
