Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2023-08, with the labels that each got.

#317 Handle SIGINT (Ctrl+C)
  CHANGELOG.md
  src/AzureAuth/Program.cs
Labels: enhancement

#315 Enable Linux release from ADO.
  .github/workflows/release.yml
  CHANGELOG.md
  bin/sign.py
  bin/trigger_azure_pipelines.py
Labels: devops

#318 Enable dependabot to track Lasso and MSAL
  .github/dependabot.yml
Labels: enhancement, devops

#325 Remove debian revision
  .github/workflows/release.yml
Labels: devops

#327 Include extra scopes and update CHANGELOG/README for 0.8.3 release
  CHANGELOG.md
  README.md
  src/AdoPat/Scopes.cs
Labels: enhancement

#329 Fix the download path of Linux artifact
  .github/workflows/release.yml
Labels: bug, devops
