Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2023-04, with the labels that each got.

#256 Read registry key for application insights token
  CHANGELOG.md
  README.md
  src/AzureAuth/EnvVars.cs
  src/AzureAuth/Program.cs
Labels: documentation, enhancement

#207 Update signing script to use keycodes specific to the given platform
  bin/sign.py
Labels: devops

#262 Release 0.7.4
  CHANGELOG.md
Labels: documentation

#255 Enforce AuthFlow Name usage and improve names for telemetry
  src/MSALWrapper.Test/AuthFlow/AuthFlowExecutorTest.cs
  src/MSALWrapper.Test/AuthFlow/AuthFlowResultTest.cs
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper/AuthFlow/AuthFlowBase.cs
  src/MSALWrapper/AuthFlow/AuthFlowResult.cs
  src/MSALWrapper/AuthFlow/Broker.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
  src/MSALWrapper/AuthFlow/Web.cs
Labels: enhancement

#264 Update README.md for 0.7.4
  README.md
Labels: documentation

#265 Remove extraneous installation step in README.md
  README.md
Labels: documentation

#260 Implement azureauth ado pat subcommand
  src/AzureAuth/Ado/Constants.cs
  src/AzureAuth/AzureAuth.csproj
  src/AzureAuth/Commands/Ado/CommandPat.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/AzureAuth/Commands/CommandAdo.cs
  src/AzureAuth/Constants.cs
Labels: enhancement

#267 Prepare for Release 0.8.0
  CHANGELOG.md
  src/AzureAuth/Commands/CommandAzureAuth.cs
  src/MSALWrapper/AuthParameters.cs
Labels: enhancement

#272 Set up CI with Azure Pipelines
  .github/workflows/azure-devops-pipelines-cg.yml
Labels: enhancement, devops

#268 chmod + x scripts
  bin/mac/azureauth
  bin/mac/dotnet
  bin/mac/publish
Labels: devops

#274 Azure pipelines patch
  .github/workflows/azure-devops-pipelines-cg.yml
Labels: bug, devops

#276 ado token command: add default value for --domain of microsoft
  CHANGELOG.md
  src/AzureAuth/Commands/Ado/CommandToken.cs
Labels: bug

#269 Ensure PAT cache keys are deterministic regardless of scope order
  src/AdoPat.Test/PatManagerTest.cs
  src/AdoPat.Test/PatOptionsTest.cs
  src/AdoPat/PatOptions.cs
Labels: bug

#270 Remove uploading codeql result in release pipeline
  .github/workflows/release.yml
Labels: bug

#281 Cleanly log catastrophic errors
  src/AzureAuth/AzureAuth.csproj
  src/AzureAuth/Commands/Ado/CommandPat.cs
Labels: enhancement

#277 🤖 [2/n] Null Accounts: Update Broker
  src/MSALWrapper.Test/AuthFlow/BrokerTest.cs
  src/MSALWrapper/AuthFlow/Broker.cs
Labels: bug

#278 🕸️ [3/n] Null Accounts: Update Web to use CachedAuth
  src/MSALWrapper.Test/AuthFlow/WebTest.cs
  src/MSALWrapper/AuthFlow/Web.cs
Labels: bug

#279 🪟 [4/n] Null Accounts: Update IWA to use CachedAuth
  src/MSALWrapper.Test/AuthFlow/IntegratedWindowsAuthenticationTest.cs
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
Labels: bug

#280 📱[5/n] Null Accounts: Update Device Code Flow
  src/MSALWrapper.Test/AuthFlow/DeviceCodeTest.cs
  src/MSALWrapper/AuthFlow/DeviceCode.cs
Labels: bug

#285 Improve ADO PAT debug logging
  src/AdoPat.Test/AdoPat.Test.csproj
  src/AdoPat.Test/PatManagerTest.cs
  src/AdoPat/AdoPat.csproj
  src/AdoPat/PatManager.cs
  src/AdoPat/PatOptions.cs
  src/AzureAuth/Commands/Ado/CommandPat.cs
Labels: enhancement
