Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2023-02, with the labels that each got.

#186 Upgrade to C# 10.0
  Directory.Build.props
  src/MSALWrapper/MSALWrapper.csproj
Labels: enhancement

#189 Migrate to Sub-Commands!
  src/AzureAuth.Test/AzureAuth.Test.csproj
  src/AzureAuth.Test/CommandAadTest.cs
  src/AzureAuth/Commands/Ado/CommandPat.cs
  src/AzureAuth/Commands/Ado/CommandToken.cs
  src/AzureAuth/Commands/CommandAad.cs
  src/AzureAuth/Commands/CommandAdo.cs
  src/AzureAuth/Commands/CommandAzureAuth.cs
  src/AzureAuth/ExceptionListToStringConverter.cs
  src/AzureAuth/Program.cs
  src/stylecop/GlobalSuppressions.cs
Labels: enhancement, refactor

#187 Upgrade lasso and use incognito mode.
  CHANGELOG.md
  src/AzureAuth.Test/AzureAuth.Test.csproj
  src/AzureAuth/AzureAuth.csproj
  src/AzureAuth/Commands/CommandAzureAuth.cs
  src/AzureAuth/Commands/CommandInfo.cs
  src/AzureAuth/Commands/Info/CommandInfoResetDeviceID.cs
  src/AzureAuth/ExceptionListToStringConverter.cs
  src/AzureAuth/Program.cs
Labels: enhancement

#192 Make top level command backwards compatible for now.
  src/AzureAuth/Commands/CommandAzureAuth.cs
Labels: enhancement, refactor

#191 Update Changelog with recent features done and in progress.
  .vscode/settings.json
  CHANGELOG.md
Labels: documentation

#200 Dogfood azureauth for nuget auth
  .github/workflows/dotnet-test.yml
  .github/workflows/release.yml
  bin/azureauth
  bin/azureauth.cmd
  bin/dotnet
  bin/dotnet.cmd
  nuget.config
Labels: devops

#202 Update Lasso
  CHANGELOG.md
  src/AzureAuth/AzureAuth.csproj
Labels: enhancement

#201 Ship release 0.7.0
  CHANGELOG.md
  src/AzureAuth/Commands/CommandAzureAuth.cs
Labels: enhancement

#204 Fix Release CI
  .github/workflows/release.yml
Labels: devops

#205 Use restore on publish but set auth token so it works
  .github/workflows/release.yml
Labels: devops

#194 Always add a newline before the path install on Mac.
  install/install.sh
Labels: bug

#203 [Unlit] Add options to the `ado token` command
  .vscode/settings.json
  src/AzureAuth/Ado/Constants.cs
  src/AzureAuth/Commands/Ado/CommandToken.cs
  src/AzureAuth/Commands/CommandAad.cs
Labels: enhancement
