Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2023-06, with the labels that each got.

#309 Update release workflow to release Linux binaries.
  .github/workflows/release.yml
Labels: enhancement, devops

#310 Add scopes validation
  src/AdoPat.Test/PatManagerTest.cs
  src/AdoPat.Test/PatOptionsTest.cs
  src/AdoPat.Test/ScopesTest.cs
  src/AdoPat/Constants.cs
  src/AdoPat/PatOptions.cs
  src/AdoPat/Scopes.cs
  src/AzureAuth/Commands/Ado/CommandPat.cs
Labels: enhancement

#311 Allow pat and token subcommands to use custom tenant
  src/AzureAuth/Ado/AuthParameters.cs
  src/AzureAuth/Ado/Constants.cs
  src/AzureAuth/Commands/Ado/CommandPat.cs
  src/AzureAuth/Commands/Ado/CommandToken.cs
Labels: enhancement

#312 Update usage documentation with new subcommands
  docs/usage.md
Labels: documentation
