Repository AzureAD/microsoft-authentication-cli, pull requests merged in 2024-04, with the labels that each got.

#372 Clarify IWA warning status
  CHANGELOG.md
  src/MSALWrapper/AuthFlow/IntegratedWindowsAuthentication.cs
Labels: enhancement

#374 Upgrade MSAL dependencies to 4.59.1
  CHANGELOG.md
  src/AdoPat/AdoPat.csproj
  src/MSALWrapper.Benchmark/MSALWrapper.Benchmark.csproj
  src/MSALWrapper/MSALWrapper.csproj
Labels: dependencies

#375 Improvements to the README doc
  README.md
Labels: documentation
